# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
latex: false
cache: packages
dist: xenial

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel
